//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Force_Time {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class opcConfic : global::System.Configuration.ApplicationSettingsBase {
        
        private static opcConfic defaultInstance = ((opcConfic)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new opcConfic())));
        
        public static opcConfic Default {
            get {
                return defaultInstance;
            }
        }
    }
}
